# Site Settings
locale                   : "en-UK"
title                    : "Sourav Mohapatra"
title_separator          : "-"
name                     : &name "Sourav Mohapatra"
description              : &description "Senior Software Engineer at ARM | Embedded Systems Specialist"
url                      : https://souravmohapatra.github.io
baseurl                  : ""
repository               : "souravmohapatra.github.io"
breadcrumbs              : true
words_per_minute         : 160
future                   : true
read_more                : "enabled"
talkmap_link             : false

# Social Sharing
social:
  type: Person
  name: "Sourav Mohapatra"
  links:
    - "https://linkedin.com/in/souravmohapatra"
    - "https://github.com/souravmohapatra"
    - "https://scholar.google.com/citations?user=9c6V7nwAAAAJ&hl=en"
    - "https://www.researchgate.net/profile/Sourav_Mohapatra3"
    - "https://www.instagram.com/sourav.mohapatra_/"

# Analytics (Optional — add your tracking ID if you want)
analytics:
  provider: "google-universal"
  google:
    tracking_id: ""

# Site Author
author:
  name: "Sourav Mohapatra"
  avatar: "self.jpg"
  bio: "Senior Software Engineer at ARM | Ex-ASML, Qualcomm | MSc Embedded Systems, TU Delft"
  location: "Cambridge, UK"
  employer: "ARM Ltd."
  googlescholar: "https://scholar.google.com/citations?user=9c6V7nwAAAAJ&hl=en"
  email: "sm.sourav.mohapatra@gmail.com"
  researchgate: "https://www.researchgate.net/profile/Sourav_Mohapatra3"
  github: "souravmohapatra"
  instagram: "sourav.mohapatra_"
  linkedin: "https://linkedin.com/in/souravmohapatra"
  orcid: "http://orcid.org/yourorcidurl"

# Additional Recommended Settings
permalink: /:categories/:title/
timezone: Europe/London

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Category and Tag Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Sass/SCSS (Optional improvement for later styling)
sass:
  sass_dir: _sass
  style: compressed

# Markdown Settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false

# Conversion Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

